/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/zhen/Documents/ros_zhen/src/table_object/srv/detect_touch_update.srv
 *
 */


#ifndef TABLE_OBJECT_MESSAGE_DETECT_TOUCH_UPDATERESPONSE_H
#define TABLE_OBJECT_MESSAGE_DETECT_TOUCH_UPDATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace table_object
{
template <class ContainerAllocator>
struct detect_touch_updateResponse_
{
  typedef detect_touch_updateResponse_<ContainerAllocator> Type;

  detect_touch_updateResponse_()
    : bottle_hand(false)
    , bottle_tabletop(false)
    , hand_tabletop(false)
    , new_detector(false)
    , succeed(false)  {
    }
  detect_touch_updateResponse_(const ContainerAllocator& _alloc)
    : bottle_hand(false)
    , bottle_tabletop(false)
    , hand_tabletop(false)
    , new_detector(false)
    , succeed(false)  {
    }



   typedef uint8_t _bottle_hand_type;
  _bottle_hand_type bottle_hand;

   typedef uint8_t _bottle_tabletop_type;
  _bottle_tabletop_type bottle_tabletop;

   typedef uint8_t _hand_tabletop_type;
  _hand_tabletop_type hand_tabletop;

   typedef uint8_t _new_detector_type;
  _new_detector_type new_detector;

   typedef uint8_t _succeed_type;
  _succeed_type succeed;




  typedef boost::shared_ptr< ::table_object::detect_touch_updateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::table_object::detect_touch_updateResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct detect_touch_updateResponse_

typedef ::table_object::detect_touch_updateResponse_<std::allocator<void> > detect_touch_updateResponse;

typedef boost::shared_ptr< ::table_object::detect_touch_updateResponse > detect_touch_updateResponsePtr;
typedef boost::shared_ptr< ::table_object::detect_touch_updateResponse const> detect_touch_updateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::table_object::detect_touch_updateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace table_object

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'household_objects_database_msgs': ['/opt/ros/groovy/share/household_objects_database_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/groovy/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/groovy/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/groovy/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/groovy/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/groovy/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/groovy/share/octomap_msgs/cmake/../msg'], 'manipulation_msgs': ['/opt/ros/groovy/share/manipulation_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/cmake/../msg'], 'table_object': ['/home/zhen/Documents/ros_zhen/src/table_object/msg'], 'actionlib_msgs': ['/opt/ros/groovy/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::table_object::detect_touch_updateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::table_object::detect_touch_updateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::table_object::detect_touch_updateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c018f549eeeedb3d5539cd56b49fac18";
  }

  static const char* value(const ::table_object::detect_touch_updateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc018f549eeeedb3dULL;
  static const uint64_t static_value2 = 0x5539cd56b49fac18ULL;
};

template<class ContainerAllocator>
struct DataType< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "table_object/detect_touch_updateResponse";
  }

  static const char* value(const ::table_object::detect_touch_updateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool bottle_hand\n\
bool bottle_tabletop\n\
bool hand_tabletop\n\
bool new_detector\n\
bool succeed\n\
\n\
\n\
";
  }

  static const char* value(const ::table_object::detect_touch_updateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bottle_hand);
      stream.next(m.bottle_tabletop);
      stream.next(m.hand_tabletop);
      stream.next(m.new_detector);
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct detect_touch_updateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::table_object::detect_touch_updateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::table_object::detect_touch_updateResponse_<ContainerAllocator>& v)
  {
    s << indent << "bottle_hand: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bottle_hand);
    s << indent << "bottle_tabletop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bottle_tabletop);
    s << indent << "hand_tabletop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hand_tabletop);
    s << indent << "new_detector: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.new_detector);
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TABLE_OBJECT_MESSAGE_DETECT_TOUCH_UPDATERESPONSE_H
