/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/zhen/Documents/ros_zhen/src/table_object/srv/detect_touch.srv
 *
 */


#ifndef TABLE_OBJECT_MESSAGE_DETECT_TOUCH_H
#define TABLE_OBJECT_MESSAGE_DETECT_TOUCH_H

#include <ros/service_traits.h>


#include <table_object/detect_touchRequest.h>
#include <table_object/detect_touchResponse.h>


namespace table_object
{

struct detect_touch
{

typedef detect_touchRequest Request;
typedef detect_touchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detect_touch
} // namespace table_object


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::table_object::detect_touch > {
  static const char* value()
  {
    return "4b6bc19218307ae9e42b6a02a0652241";
  }

  static const char* value(const ::table_object::detect_touch&) { return value(); }
};

template<>
struct DataType< ::table_object::detect_touch > {
  static const char* value()
  {
    return "table_object/detect_touch";
  }

  static const char* value(const ::table_object::detect_touch&) { return value(); }
};


// service_traits::MD5Sum< ::table_object::detect_touchRequest> should match 
// service_traits::MD5Sum< ::table_object::detect_touch > 
template<>
struct MD5Sum< ::table_object::detect_touchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::table_object::detect_touch >::value();
  }
  static const char* value(const ::table_object::detect_touchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::table_object::detect_touchRequest> should match 
// service_traits::DataType< ::table_object::detect_touch > 
template<>
struct DataType< ::table_object::detect_touchRequest>
{
  static const char* value()
  {
    return DataType< ::table_object::detect_touch >::value();
  }
  static const char* value(const ::table_object::detect_touchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::table_object::detect_touchResponse> should match 
// service_traits::MD5Sum< ::table_object::detect_touch > 
template<>
struct MD5Sum< ::table_object::detect_touchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::table_object::detect_touch >::value();
  }
  static const char* value(const ::table_object::detect_touchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::table_object::detect_touchResponse> should match 
// service_traits::DataType< ::table_object::detect_touch > 
template<>
struct DataType< ::table_object::detect_touchResponse>
{
  static const char* value()
  {
    return DataType< ::table_object::detect_touch >::value();
  }
  static const char* value(const ::table_object::detect_touchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TABLE_OBJECT_MESSAGE_DETECT_TOUCH_H
